### ISSUE TITLE
Code value to State not working as expected

### ISSUE THREAD

**Issue by thyagarajarahul** [Twotalltotems/react-native-otp-input#6] opened 2019-07-31 16:03 UTC
onCodeFilled works only when the UI is filled. I use this function store the code in state. If I delete the code and check the value the code is still present in the state which is not how it is supposed to work as it violates validation. There has to be another function which is triggered when the code is delete one-by-one or the current onCodeFilled has to trigger for every single input instead of it's current working.

Thanks.

**Comment by ansonyao** [comment] 2019-07-31 17:09
Hey @rahulthyagaraja1, thanks for the suggestion! I agree that it does not support code validation at this point. The reason is that this component was designed to work in an uncontrolled manner at this point, while I think we need to make this component to support working in a controlled manner for validation purpose. Will try to add it in the next release.

**Comment by rahulthyagaraja1** [comment] 2019-07-31 17:12
Thank you for taking my suggestion. But for the time being I will stop using your component for another one. But it's a shame cause yours was the best out of all the ones I tried. The one I am going with now needs a lot of customization and it's not worth it. Anyway thanks.

**Comment by ansonyao** [comment] 2019-07-31 17:19
Yeah, for sure. Will update here when it is done. Thanks again for the suggestions!

**Comment by ansonyao** [comment] 2019-08-19 22:52
Have just published v1.1.0. Now you can use this component as a controlled component by providing property `code`. I will close this issue for now. @thyagarajarahul.

**Closed by ansonyao** 2019-08-19 22:52 UTC
